# Generated by Django 6.0 on 2025-12-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('emissions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emission_type', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Emission',
                'verbose_name_plural': 'Emissions',
                'ordering': ['year', 'country', 'emission_type'],
            },
        ),
    ]
